# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Track_your_steps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Track_your_steps
Pod 'Charts'
  target 'Track_your_stepsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
